# Generated by Django 4.0.4 on 2022-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('open_time', models.TextField(blank=True, null=True)),
                ('close_time', models.TextField(blank=True, null=True)),
                ('business_time', models.TextField(blank=True, null=True)),
                ('regular_dayoff', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('g_speciality', models.IntegerField(blank=True, null=True)),
                ('g_shopping', models.IntegerField(blank=True, null=True)),
                ('g_hotel', models.IntegerField(blank=True, null=True)),
                ('g_sightseeing', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spot',
                'managed': False,
            },
        ),
    ]
